# Generated by Django 4.1.7 on 2023-02-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_age_group'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='offering_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_book', to='book.book'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='requested_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_book', to='book.book'),
        ),
    ]
