# Generated by Django 4.1.7 on 2023-02-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_agegroupcathegory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeGroupCathegory',
            new_name='AgeGroupCategory',
        ),
    ]
