# Generated by Django 4.1.7 on 2023-02-18 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_agegroupcathegory_agegroupcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroupcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Age Group Categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.agegroupcategory'),
        ),
    ]
