# Generated by Django 4.1.7 on 2023-02-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_agegroupcategory_options_book_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='books', to='book.agegroupcategory'),
        ),
    ]
